// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packages.proto

package com.chaoslabgames.packet;

/**
 * Protobuf type {@code com.chaoslabgames.packet.JoinEventPkg}
 */
public final class JoinEventPkg extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.chaoslabgames.packet.JoinEventPkg)
    JoinEventPkgOrBuilder {
  // Use JoinEventPkg.newBuilder() to construct.
  private JoinEventPkg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private JoinEventPkg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final JoinEventPkg defaultInstance;
  public static JoinEventPkg getDefaultInstance() {
    return defaultInstance;
  }

  public JoinEventPkg getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private JoinEventPkg(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            bitField0_ |= 0x00000001;
            id_ = input.readInt64();
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000002;
            name_ = bs;
            break;
          }
          case 26: {
            com.chaoslabgames.packet.MoverDataPkg.Builder subBuilder = null;
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
              subBuilder = data_.toBuilder();
            }
            data_ = input.readMessage(com.chaoslabgames.packet.MoverDataPkg.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(data_);
              data_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000004;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.chaoslabgames.packet.Packet.internal_static_com_chaoslabgames_packet_JoinEventPkg_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.chaoslabgames.packet.Packet.internal_static_com_chaoslabgames_packet_JoinEventPkg_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.chaoslabgames.packet.JoinEventPkg.class, com.chaoslabgames.packet.JoinEventPkg.Builder.class);
  }

  public static com.google.protobuf.Parser<JoinEventPkg> PARSER =
      new com.google.protobuf.AbstractParser<JoinEventPkg>() {
    public JoinEventPkg parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new JoinEventPkg(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<JoinEventPkg> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>required int64 id = 1;</code>
   */
  public boolean hasId() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required int64 id = 1;</code>
   */
  public long getId() {
    return id_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private java.lang.Object name_;
  /**
   * <code>required string name = 2;</code>
   */
  public boolean hasName() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>required string name = 2;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        name_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string name = 2;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATA_FIELD_NUMBER = 3;
  private com.chaoslabgames.packet.MoverDataPkg data_;
  /**
   * <code>required .com.chaoslabgames.packet.MoverDataPkg data = 3;</code>
   */
  public boolean hasData() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>required .com.chaoslabgames.packet.MoverDataPkg data = 3;</code>
   */
  public com.chaoslabgames.packet.MoverDataPkg getData() {
    return data_;
  }
  /**
   * <code>required .com.chaoslabgames.packet.MoverDataPkg data = 3;</code>
   */
  public com.chaoslabgames.packet.MoverDataPkgOrBuilder getDataOrBuilder() {
    return data_;
  }

  private void initFields() {
    id_ = 0L;
    name_ = "";
    data_ = com.chaoslabgames.packet.MoverDataPkg.getDefaultInstance();
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasId()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasName()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasData()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!getData().isInitialized()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeInt64(1, id_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeBytes(2, getNameBytes());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeMessage(3, data_);
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, getNameBytes());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, data_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static com.chaoslabgames.packet.JoinEventPkg parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.chaoslabgames.packet.JoinEventPkg parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.chaoslabgames.packet.JoinEventPkg parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.chaoslabgames.packet.JoinEventPkg parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.chaoslabgames.packet.JoinEventPkg parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.chaoslabgames.packet.JoinEventPkg parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.chaoslabgames.packet.JoinEventPkg parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.chaoslabgames.packet.JoinEventPkg parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.chaoslabgames.packet.JoinEventPkg parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.chaoslabgames.packet.JoinEventPkg parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.chaoslabgames.packet.JoinEventPkg prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.chaoslabgames.packet.JoinEventPkg}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.chaoslabgames.packet.JoinEventPkg)
      com.chaoslabgames.packet.JoinEventPkgOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.chaoslabgames.packet.Packet.internal_static_com_chaoslabgames_packet_JoinEventPkg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.chaoslabgames.packet.Packet.internal_static_com_chaoslabgames_packet_JoinEventPkg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.chaoslabgames.packet.JoinEventPkg.class, com.chaoslabgames.packet.JoinEventPkg.Builder.class);
    }

    // Construct using com.chaoslabgames.packet.JoinEventPkg.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getDataFieldBuilder();
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      id_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      name_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      if (dataBuilder_ == null) {
        data_ = com.chaoslabgames.packet.MoverDataPkg.getDefaultInstance();
      } else {
        dataBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.chaoslabgames.packet.Packet.internal_static_com_chaoslabgames_packet_JoinEventPkg_descriptor;
    }

    public com.chaoslabgames.packet.JoinEventPkg getDefaultInstanceForType() {
      return com.chaoslabgames.packet.JoinEventPkg.getDefaultInstance();
    }

    public com.chaoslabgames.packet.JoinEventPkg build() {
      com.chaoslabgames.packet.JoinEventPkg result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.chaoslabgames.packet.JoinEventPkg buildPartial() {
      com.chaoslabgames.packet.JoinEventPkg result = new com.chaoslabgames.packet.JoinEventPkg(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.id_ = id_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.name_ = name_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      if (dataBuilder_ == null) {
        result.data_ = data_;
      } else {
        result.data_ = dataBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.chaoslabgames.packet.JoinEventPkg) {
        return mergeFrom((com.chaoslabgames.packet.JoinEventPkg)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.chaoslabgames.packet.JoinEventPkg other) {
      if (other == com.chaoslabgames.packet.JoinEventPkg.getDefaultInstance()) return this;
      if (other.hasId()) {
        setId(other.getId());
      }
      if (other.hasName()) {
        bitField0_ |= 0x00000002;
        name_ = other.name_;
        onChanged();
      }
      if (other.hasData()) {
        mergeData(other.getData());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasId()) {
        
        return false;
      }
      if (!hasName()) {
        
        return false;
      }
      if (!hasData()) {
        
        return false;
      }
      if (!getData().isInitialized()) {
        
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.chaoslabgames.packet.JoinEventPkg parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.chaoslabgames.packet.JoinEventPkg) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long id_ ;
    /**
     * <code>required int64 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }
    /**
     * <code>required int64 id = 1;</code>
     */
    public Builder setId(long value) {
      bitField0_ |= 0x00000001;
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int64 id = 1;</code>
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>required string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string name = 2;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string name = 2;</code>
     */
    public Builder clearName() {
      bitField0_ = (bitField0_ & ~0x00000002);
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>required string name = 2;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      name_ = value;
      onChanged();
      return this;
    }

    private com.chaoslabgames.packet.MoverDataPkg data_ = com.chaoslabgames.packet.MoverDataPkg.getDefaultInstance();
    private com.google.protobuf.SingleFieldBuilder<
        com.chaoslabgames.packet.MoverDataPkg, com.chaoslabgames.packet.MoverDataPkg.Builder, com.chaoslabgames.packet.MoverDataPkgOrBuilder> dataBuilder_;
    /**
     * <code>required .com.chaoslabgames.packet.MoverDataPkg data = 3;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .com.chaoslabgames.packet.MoverDataPkg data = 3;</code>
     */
    public com.chaoslabgames.packet.MoverDataPkg getData() {
      if (dataBuilder_ == null) {
        return data_;
      } else {
        return dataBuilder_.getMessage();
      }
    }
    /**
     * <code>required .com.chaoslabgames.packet.MoverDataPkg data = 3;</code>
     */
    public Builder setData(com.chaoslabgames.packet.MoverDataPkg value) {
      if (dataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
        onChanged();
      } else {
        dataBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>required .com.chaoslabgames.packet.MoverDataPkg data = 3;</code>
     */
    public Builder setData(
        com.chaoslabgames.packet.MoverDataPkg.Builder builderForValue) {
      if (dataBuilder_ == null) {
        data_ = builderForValue.build();
        onChanged();
      } else {
        dataBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>required .com.chaoslabgames.packet.MoverDataPkg data = 3;</code>
     */
    public Builder mergeData(com.chaoslabgames.packet.MoverDataPkg value) {
      if (dataBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004) &&
            data_ != com.chaoslabgames.packet.MoverDataPkg.getDefaultInstance()) {
          data_ =
            com.chaoslabgames.packet.MoverDataPkg.newBuilder(data_).mergeFrom(value).buildPartial();
        } else {
          data_ = value;
        }
        onChanged();
      } else {
        dataBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>required .com.chaoslabgames.packet.MoverDataPkg data = 3;</code>
     */
    public Builder clearData() {
      if (dataBuilder_ == null) {
        data_ = com.chaoslabgames.packet.MoverDataPkg.getDefaultInstance();
        onChanged();
      } else {
        dataBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }
    /**
     * <code>required .com.chaoslabgames.packet.MoverDataPkg data = 3;</code>
     */
    public com.chaoslabgames.packet.MoverDataPkg.Builder getDataBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getDataFieldBuilder().getBuilder();
    }
    /**
     * <code>required .com.chaoslabgames.packet.MoverDataPkg data = 3;</code>
     */
    public com.chaoslabgames.packet.MoverDataPkgOrBuilder getDataOrBuilder() {
      if (dataBuilder_ != null) {
        return dataBuilder_.getMessageOrBuilder();
      } else {
        return data_;
      }
    }
    /**
     * <code>required .com.chaoslabgames.packet.MoverDataPkg data = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.chaoslabgames.packet.MoverDataPkg, com.chaoslabgames.packet.MoverDataPkg.Builder, com.chaoslabgames.packet.MoverDataPkgOrBuilder> 
        getDataFieldBuilder() {
      if (dataBuilder_ == null) {
        dataBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.chaoslabgames.packet.MoverDataPkg, com.chaoslabgames.packet.MoverDataPkg.Builder, com.chaoslabgames.packet.MoverDataPkgOrBuilder>(
                getData(),
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      return dataBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:com.chaoslabgames.packet.JoinEventPkg)
  }

  static {
    defaultInstance = new JoinEventPkg(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:com.chaoslabgames.packet.JoinEventPkg)
}

