// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packages.proto

package com.chaoslabgames.packet;

public interface JoinEventPkgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.chaoslabgames.packet.JoinEventPkg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int64 id = 1;</code>
   */
  boolean hasId();
  /**
   * <code>required int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>required string name = 2;</code>
   */
  boolean hasName();
  /**
   * <code>required string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>required string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>required .com.chaoslabgames.packet.MoverDataPkg data = 3;</code>
   */
  boolean hasData();
  /**
   * <code>required .com.chaoslabgames.packet.MoverDataPkg data = 3;</code>
   */
  com.chaoslabgames.packet.MoverDataPkg getData();
  /**
   * <code>required .com.chaoslabgames.packet.MoverDataPkg data = 3;</code>
   */
  com.chaoslabgames.packet.MoverDataPkgOrBuilder getDataOrBuilder();
}
