// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packages.proto

package com.chaoslabgames.packet;

/**
 * Protobuf type {@code com.chaoslabgames.packet.MoverDataPkg}
 */
public final class MoverDataPkg extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.chaoslabgames.packet.MoverDataPkg)
    MoverDataPkgOrBuilder {
  // Use MoverDataPkg.newBuilder() to construct.
  private MoverDataPkg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private MoverDataPkg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final MoverDataPkg defaultInstance;
  public static MoverDataPkg getDefaultInstance() {
    return defaultInstance;
  }

  public MoverDataPkg getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private MoverDataPkg(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.chaoslabgames.packet.PointPkg.Builder subBuilder = null;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
              subBuilder = position_.toBuilder();
            }
            position_ = input.readMessage(com.chaoslabgames.packet.PointPkg.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(position_);
              position_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000001;
            break;
          }
          case 18: {
            com.chaoslabgames.packet.PointPkg.Builder subBuilder = null;
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
              subBuilder = direction_.toBuilder();
            }
            direction_ = input.readMessage(com.chaoslabgames.packet.PointPkg.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(direction_);
              direction_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000002;
            break;
          }
          case 24: {
            bitField0_ |= 0x00000004;
            color_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.chaoslabgames.packet.Packet.internal_static_com_chaoslabgames_packet_MoverDataPkg_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.chaoslabgames.packet.Packet.internal_static_com_chaoslabgames_packet_MoverDataPkg_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.chaoslabgames.packet.MoverDataPkg.class, com.chaoslabgames.packet.MoverDataPkg.Builder.class);
  }

  public static com.google.protobuf.Parser<MoverDataPkg> PARSER =
      new com.google.protobuf.AbstractParser<MoverDataPkg>() {
    public MoverDataPkg parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MoverDataPkg(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<MoverDataPkg> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  public static final int POSITION_FIELD_NUMBER = 1;
  private com.chaoslabgames.packet.PointPkg position_;
  /**
   * <code>required .com.chaoslabgames.packet.PointPkg position = 1;</code>
   */
  public boolean hasPosition() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required .com.chaoslabgames.packet.PointPkg position = 1;</code>
   */
  public com.chaoslabgames.packet.PointPkg getPosition() {
    return position_;
  }
  /**
   * <code>required .com.chaoslabgames.packet.PointPkg position = 1;</code>
   */
  public com.chaoslabgames.packet.PointPkgOrBuilder getPositionOrBuilder() {
    return position_;
  }

  public static final int DIRECTION_FIELD_NUMBER = 2;
  private com.chaoslabgames.packet.PointPkg direction_;
  /**
   * <code>required .com.chaoslabgames.packet.PointPkg direction = 2;</code>
   */
  public boolean hasDirection() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>required .com.chaoslabgames.packet.PointPkg direction = 2;</code>
   */
  public com.chaoslabgames.packet.PointPkg getDirection() {
    return direction_;
  }
  /**
   * <code>required .com.chaoslabgames.packet.PointPkg direction = 2;</code>
   */
  public com.chaoslabgames.packet.PointPkgOrBuilder getDirectionOrBuilder() {
    return direction_;
  }

  public static final int COLOR_FIELD_NUMBER = 3;
  private int color_;
  /**
   * <code>required int32 color = 3;</code>
   */
  public boolean hasColor() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>required int32 color = 3;</code>
   */
  public int getColor() {
    return color_;
  }

  private void initFields() {
    position_ = com.chaoslabgames.packet.PointPkg.getDefaultInstance();
    direction_ = com.chaoslabgames.packet.PointPkg.getDefaultInstance();
    color_ = 0;
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasPosition()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasDirection()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasColor()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!getPosition().isInitialized()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!getDirection().isInitialized()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeMessage(1, position_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeMessage(2, direction_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeInt32(3, color_);
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, position_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, direction_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, color_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static com.chaoslabgames.packet.MoverDataPkg parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.chaoslabgames.packet.MoverDataPkg parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.chaoslabgames.packet.MoverDataPkg parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.chaoslabgames.packet.MoverDataPkg parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.chaoslabgames.packet.MoverDataPkg parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.chaoslabgames.packet.MoverDataPkg parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.chaoslabgames.packet.MoverDataPkg parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.chaoslabgames.packet.MoverDataPkg parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.chaoslabgames.packet.MoverDataPkg parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.chaoslabgames.packet.MoverDataPkg parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.chaoslabgames.packet.MoverDataPkg prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.chaoslabgames.packet.MoverDataPkg}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.chaoslabgames.packet.MoverDataPkg)
      com.chaoslabgames.packet.MoverDataPkgOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.chaoslabgames.packet.Packet.internal_static_com_chaoslabgames_packet_MoverDataPkg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.chaoslabgames.packet.Packet.internal_static_com_chaoslabgames_packet_MoverDataPkg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.chaoslabgames.packet.MoverDataPkg.class, com.chaoslabgames.packet.MoverDataPkg.Builder.class);
    }

    // Construct using com.chaoslabgames.packet.MoverDataPkg.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getPositionFieldBuilder();
        getDirectionFieldBuilder();
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      if (positionBuilder_ == null) {
        position_ = com.chaoslabgames.packet.PointPkg.getDefaultInstance();
      } else {
        positionBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      if (directionBuilder_ == null) {
        direction_ = com.chaoslabgames.packet.PointPkg.getDefaultInstance();
      } else {
        directionBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      color_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.chaoslabgames.packet.Packet.internal_static_com_chaoslabgames_packet_MoverDataPkg_descriptor;
    }

    public com.chaoslabgames.packet.MoverDataPkg getDefaultInstanceForType() {
      return com.chaoslabgames.packet.MoverDataPkg.getDefaultInstance();
    }

    public com.chaoslabgames.packet.MoverDataPkg build() {
      com.chaoslabgames.packet.MoverDataPkg result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.chaoslabgames.packet.MoverDataPkg buildPartial() {
      com.chaoslabgames.packet.MoverDataPkg result = new com.chaoslabgames.packet.MoverDataPkg(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      if (positionBuilder_ == null) {
        result.position_ = position_;
      } else {
        result.position_ = positionBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      if (directionBuilder_ == null) {
        result.direction_ = direction_;
      } else {
        result.direction_ = directionBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.color_ = color_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.chaoslabgames.packet.MoverDataPkg) {
        return mergeFrom((com.chaoslabgames.packet.MoverDataPkg)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.chaoslabgames.packet.MoverDataPkg other) {
      if (other == com.chaoslabgames.packet.MoverDataPkg.getDefaultInstance()) return this;
      if (other.hasPosition()) {
        mergePosition(other.getPosition());
      }
      if (other.hasDirection()) {
        mergeDirection(other.getDirection());
      }
      if (other.hasColor()) {
        setColor(other.getColor());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasPosition()) {
        
        return false;
      }
      if (!hasDirection()) {
        
        return false;
      }
      if (!hasColor()) {
        
        return false;
      }
      if (!getPosition().isInitialized()) {
        
        return false;
      }
      if (!getDirection().isInitialized()) {
        
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.chaoslabgames.packet.MoverDataPkg parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.chaoslabgames.packet.MoverDataPkg) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.chaoslabgames.packet.PointPkg position_ = com.chaoslabgames.packet.PointPkg.getDefaultInstance();
    private com.google.protobuf.SingleFieldBuilder<
        com.chaoslabgames.packet.PointPkg, com.chaoslabgames.packet.PointPkg.Builder, com.chaoslabgames.packet.PointPkgOrBuilder> positionBuilder_;
    /**
     * <code>required .com.chaoslabgames.packet.PointPkg position = 1;</code>
     */
    public boolean hasPosition() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.chaoslabgames.packet.PointPkg position = 1;</code>
     */
    public com.chaoslabgames.packet.PointPkg getPosition() {
      if (positionBuilder_ == null) {
        return position_;
      } else {
        return positionBuilder_.getMessage();
      }
    }
    /**
     * <code>required .com.chaoslabgames.packet.PointPkg position = 1;</code>
     */
    public Builder setPosition(com.chaoslabgames.packet.PointPkg value) {
      if (positionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        position_ = value;
        onChanged();
      } else {
        positionBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>required .com.chaoslabgames.packet.PointPkg position = 1;</code>
     */
    public Builder setPosition(
        com.chaoslabgames.packet.PointPkg.Builder builderForValue) {
      if (positionBuilder_ == null) {
        position_ = builderForValue.build();
        onChanged();
      } else {
        positionBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>required .com.chaoslabgames.packet.PointPkg position = 1;</code>
     */
    public Builder mergePosition(com.chaoslabgames.packet.PointPkg value) {
      if (positionBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001) &&
            position_ != com.chaoslabgames.packet.PointPkg.getDefaultInstance()) {
          position_ =
            com.chaoslabgames.packet.PointPkg.newBuilder(position_).mergeFrom(value).buildPartial();
        } else {
          position_ = value;
        }
        onChanged();
      } else {
        positionBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>required .com.chaoslabgames.packet.PointPkg position = 1;</code>
     */
    public Builder clearPosition() {
      if (positionBuilder_ == null) {
        position_ = com.chaoslabgames.packet.PointPkg.getDefaultInstance();
        onChanged();
      } else {
        positionBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }
    /**
     * <code>required .com.chaoslabgames.packet.PointPkg position = 1;</code>
     */
    public com.chaoslabgames.packet.PointPkg.Builder getPositionBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getPositionFieldBuilder().getBuilder();
    }
    /**
     * <code>required .com.chaoslabgames.packet.PointPkg position = 1;</code>
     */
    public com.chaoslabgames.packet.PointPkgOrBuilder getPositionOrBuilder() {
      if (positionBuilder_ != null) {
        return positionBuilder_.getMessageOrBuilder();
      } else {
        return position_;
      }
    }
    /**
     * <code>required .com.chaoslabgames.packet.PointPkg position = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.chaoslabgames.packet.PointPkg, com.chaoslabgames.packet.PointPkg.Builder, com.chaoslabgames.packet.PointPkgOrBuilder> 
        getPositionFieldBuilder() {
      if (positionBuilder_ == null) {
        positionBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.chaoslabgames.packet.PointPkg, com.chaoslabgames.packet.PointPkg.Builder, com.chaoslabgames.packet.PointPkgOrBuilder>(
                getPosition(),
                getParentForChildren(),
                isClean());
        position_ = null;
      }
      return positionBuilder_;
    }

    private com.chaoslabgames.packet.PointPkg direction_ = com.chaoslabgames.packet.PointPkg.getDefaultInstance();
    private com.google.protobuf.SingleFieldBuilder<
        com.chaoslabgames.packet.PointPkg, com.chaoslabgames.packet.PointPkg.Builder, com.chaoslabgames.packet.PointPkgOrBuilder> directionBuilder_;
    /**
     * <code>required .com.chaoslabgames.packet.PointPkg direction = 2;</code>
     */
    public boolean hasDirection() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .com.chaoslabgames.packet.PointPkg direction = 2;</code>
     */
    public com.chaoslabgames.packet.PointPkg getDirection() {
      if (directionBuilder_ == null) {
        return direction_;
      } else {
        return directionBuilder_.getMessage();
      }
    }
    /**
     * <code>required .com.chaoslabgames.packet.PointPkg direction = 2;</code>
     */
    public Builder setDirection(com.chaoslabgames.packet.PointPkg value) {
      if (directionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        direction_ = value;
        onChanged();
      } else {
        directionBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>required .com.chaoslabgames.packet.PointPkg direction = 2;</code>
     */
    public Builder setDirection(
        com.chaoslabgames.packet.PointPkg.Builder builderForValue) {
      if (directionBuilder_ == null) {
        direction_ = builderForValue.build();
        onChanged();
      } else {
        directionBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>required .com.chaoslabgames.packet.PointPkg direction = 2;</code>
     */
    public Builder mergeDirection(com.chaoslabgames.packet.PointPkg value) {
      if (directionBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002) &&
            direction_ != com.chaoslabgames.packet.PointPkg.getDefaultInstance()) {
          direction_ =
            com.chaoslabgames.packet.PointPkg.newBuilder(direction_).mergeFrom(value).buildPartial();
        } else {
          direction_ = value;
        }
        onChanged();
      } else {
        directionBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>required .com.chaoslabgames.packet.PointPkg direction = 2;</code>
     */
    public Builder clearDirection() {
      if (directionBuilder_ == null) {
        direction_ = com.chaoslabgames.packet.PointPkg.getDefaultInstance();
        onChanged();
      } else {
        directionBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }
    /**
     * <code>required .com.chaoslabgames.packet.PointPkg direction = 2;</code>
     */
    public com.chaoslabgames.packet.PointPkg.Builder getDirectionBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getDirectionFieldBuilder().getBuilder();
    }
    /**
     * <code>required .com.chaoslabgames.packet.PointPkg direction = 2;</code>
     */
    public com.chaoslabgames.packet.PointPkgOrBuilder getDirectionOrBuilder() {
      if (directionBuilder_ != null) {
        return directionBuilder_.getMessageOrBuilder();
      } else {
        return direction_;
      }
    }
    /**
     * <code>required .com.chaoslabgames.packet.PointPkg direction = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.chaoslabgames.packet.PointPkg, com.chaoslabgames.packet.PointPkg.Builder, com.chaoslabgames.packet.PointPkgOrBuilder> 
        getDirectionFieldBuilder() {
      if (directionBuilder_ == null) {
        directionBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.chaoslabgames.packet.PointPkg, com.chaoslabgames.packet.PointPkg.Builder, com.chaoslabgames.packet.PointPkgOrBuilder>(
                getDirection(),
                getParentForChildren(),
                isClean());
        direction_ = null;
      }
      return directionBuilder_;
    }

    private int color_ ;
    /**
     * <code>required int32 color = 3;</code>
     */
    public boolean hasColor() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 color = 3;</code>
     */
    public int getColor() {
      return color_;
    }
    /**
     * <code>required int32 color = 3;</code>
     */
    public Builder setColor(int value) {
      bitField0_ |= 0x00000004;
      color_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 color = 3;</code>
     */
    public Builder clearColor() {
      bitField0_ = (bitField0_ & ~0x00000004);
      color_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.chaoslabgames.packet.MoverDataPkg)
  }

  static {
    defaultInstance = new MoverDataPkg(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:com.chaoslabgames.packet.MoverDataPkg)
}

