// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packages.proto

package com.chaoslabgames.packet;

public interface MoverDataPkgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.chaoslabgames.packet.MoverDataPkg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required .com.chaoslabgames.packet.PointPkg position = 1;</code>
   */
  boolean hasPosition();
  /**
   * <code>required .com.chaoslabgames.packet.PointPkg position = 1;</code>
   */
  com.chaoslabgames.packet.PointPkg getPosition();
  /**
   * <code>required .com.chaoslabgames.packet.PointPkg position = 1;</code>
   */
  com.chaoslabgames.packet.PointPkgOrBuilder getPositionOrBuilder();

  /**
   * <code>required .com.chaoslabgames.packet.PointPkg direction = 2;</code>
   */
  boolean hasDirection();
  /**
   * <code>required .com.chaoslabgames.packet.PointPkg direction = 2;</code>
   */
  com.chaoslabgames.packet.PointPkg getDirection();
  /**
   * <code>required .com.chaoslabgames.packet.PointPkg direction = 2;</code>
   */
  com.chaoslabgames.packet.PointPkgOrBuilder getDirectionOrBuilder();

  /**
   * <code>required int32 color = 3;</code>
   */
  boolean hasColor();
  /**
   * <code>required int32 color = 3;</code>
   */
  int getColor();
}
