// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packages.proto

package com.chaoslabgames.packet;

public final class Packet {
  private Packet() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_chaoslabgames_packet_PacketMSG_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_chaoslabgames_packet_PacketMSG_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_chaoslabgames_packet_LoginPkg_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_chaoslabgames_packet_LoginPkg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_chaoslabgames_packet_PointPkg_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_chaoslabgames_packet_PointPkg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_chaoslabgames_packet_MoverDataPkg_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_chaoslabgames_packet_MoverDataPkg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_chaoslabgames_packet_UpdateDirectionCmdPkg_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_chaoslabgames_packet_UpdateDirectionCmdPkg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_chaoslabgames_packet_JoinEventPkg_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_chaoslabgames_packet_JoinEventPkg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_chaoslabgames_packet_UpdateMoverEventPkg_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_chaoslabgames_packet_UpdateMoverEventPkg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016packages.proto\022\030com.chaoslabgames.pack" +
      "et\"5\n\tPacketMSG\022\014\n\004ping\030\001 \001(\010\022\014\n\004type\030\002 " +
      "\001(\005\022\014\n\004data\030\003 \001(\014\"\030\n\010LoginPkg\022\014\n\004name\030\001 " +
      "\002(\t\" \n\010PointPkg\022\t\n\001x\030\001 \002(\002\022\t\n\001y\030\002 \002(\002\"\212\001" +
      "\n\014MoverDataPkg\0224\n\010position\030\001 \002(\0132\".com.c" +
      "haoslabgames.packet.PointPkg\0225\n\tdirectio" +
      "n\030\002 \002(\0132\".com.chaoslabgames.packet.Point" +
      "Pkg\022\r\n\005color\030\003 \002(\005\"N\n\025UpdateDirectionCmd" +
      "Pkg\0225\n\tdirection\030\001 \002(\0132\".com.chaoslabgam" +
      "es.packet.PointPkg\"^\n\014JoinEventPkg\022\n\n\002id",
      "\030\001 \002(\003\022\014\n\004name\030\002 \002(\t\0224\n\004data\030\003 \002(\0132&.com" +
      ".chaoslabgames.packet.MoverDataPkg\"\\\n\023Up" +
      "dateMoverEventPkg\022\n\n\002id\030\001 \002(\003\0229\n\tmoverDa" +
      "ta\030\002 \002(\0132&.com.chaoslabgames.packet.Move" +
      "rDataPkgB$\n\030com.chaoslabgames.packetB\006Pa" +
      "cketP\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_chaoslabgames_packet_PacketMSG_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_chaoslabgames_packet_PacketMSG_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_chaoslabgames_packet_PacketMSG_descriptor,
        new java.lang.String[] { "Ping", "Type", "Data", });
    internal_static_com_chaoslabgames_packet_LoginPkg_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_chaoslabgames_packet_LoginPkg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_chaoslabgames_packet_LoginPkg_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_com_chaoslabgames_packet_PointPkg_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_chaoslabgames_packet_PointPkg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_chaoslabgames_packet_PointPkg_descriptor,
        new java.lang.String[] { "X", "Y", });
    internal_static_com_chaoslabgames_packet_MoverDataPkg_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_chaoslabgames_packet_MoverDataPkg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_chaoslabgames_packet_MoverDataPkg_descriptor,
        new java.lang.String[] { "Position", "Direction", "Color", });
    internal_static_com_chaoslabgames_packet_UpdateDirectionCmdPkg_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_chaoslabgames_packet_UpdateDirectionCmdPkg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_chaoslabgames_packet_UpdateDirectionCmdPkg_descriptor,
        new java.lang.String[] { "Direction", });
    internal_static_com_chaoslabgames_packet_JoinEventPkg_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_chaoslabgames_packet_JoinEventPkg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_chaoslabgames_packet_JoinEventPkg_descriptor,
        new java.lang.String[] { "Id", "Name", "Data", });
    internal_static_com_chaoslabgames_packet_UpdateMoverEventPkg_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_chaoslabgames_packet_UpdateMoverEventPkg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_chaoslabgames_packet_UpdateMoverEventPkg_descriptor,
        new java.lang.String[] { "Id", "MoverData", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
