// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packages.proto

package com.chaoslabgames.packet;

public interface PointPkgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.chaoslabgames.packet.PointPkg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required float x = 1;</code>
   */
  boolean hasX();
  /**
   * <code>required float x = 1;</code>
   */
  float getX();

  /**
   * <code>required float y = 2;</code>
   */
  boolean hasY();
  /**
   * <code>required float y = 2;</code>
   */
  float getY();
}
