// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packages.proto

package com.chaoslabgames.packet;

/**
 * Protobuf type {@code com.chaoslabgames.packet.UpdateDirectionCmdPkg}
 */
public final class UpdateDirectionCmdPkg extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.chaoslabgames.packet.UpdateDirectionCmdPkg)
    UpdateDirectionCmdPkgOrBuilder {
  // Use UpdateDirectionCmdPkg.newBuilder() to construct.
  private UpdateDirectionCmdPkg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private UpdateDirectionCmdPkg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final UpdateDirectionCmdPkg defaultInstance;
  public static UpdateDirectionCmdPkg getDefaultInstance() {
    return defaultInstance;
  }

  public UpdateDirectionCmdPkg getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private UpdateDirectionCmdPkg(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.chaoslabgames.packet.PointPkg.Builder subBuilder = null;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
              subBuilder = direction_.toBuilder();
            }
            direction_ = input.readMessage(com.chaoslabgames.packet.PointPkg.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(direction_);
              direction_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000001;
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            tickId_ = input.readInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.chaoslabgames.packet.Packet.internal_static_com_chaoslabgames_packet_UpdateDirectionCmdPkg_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.chaoslabgames.packet.Packet.internal_static_com_chaoslabgames_packet_UpdateDirectionCmdPkg_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.chaoslabgames.packet.UpdateDirectionCmdPkg.class, com.chaoslabgames.packet.UpdateDirectionCmdPkg.Builder.class);
  }

  public static com.google.protobuf.Parser<UpdateDirectionCmdPkg> PARSER =
      new com.google.protobuf.AbstractParser<UpdateDirectionCmdPkg>() {
    public UpdateDirectionCmdPkg parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UpdateDirectionCmdPkg(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<UpdateDirectionCmdPkg> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  public static final int DIRECTION_FIELD_NUMBER = 1;
  private com.chaoslabgames.packet.PointPkg direction_;
  /**
   * <code>required .com.chaoslabgames.packet.PointPkg direction = 1;</code>
   */
  public boolean hasDirection() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required .com.chaoslabgames.packet.PointPkg direction = 1;</code>
   */
  public com.chaoslabgames.packet.PointPkg getDirection() {
    return direction_;
  }
  /**
   * <code>required .com.chaoslabgames.packet.PointPkg direction = 1;</code>
   */
  public com.chaoslabgames.packet.PointPkgOrBuilder getDirectionOrBuilder() {
    return direction_;
  }

  public static final int TICKID_FIELD_NUMBER = 2;
  private long tickId_;
  /**
   * <code>required int64 tickId = 2;</code>
   */
  public boolean hasTickId() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>required int64 tickId = 2;</code>
   */
  public long getTickId() {
    return tickId_;
  }

  private void initFields() {
    direction_ = com.chaoslabgames.packet.PointPkg.getDefaultInstance();
    tickId_ = 0L;
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasDirection()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasTickId()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!getDirection().isInitialized()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeMessage(1, direction_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeInt64(2, tickId_);
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, direction_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, tickId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static com.chaoslabgames.packet.UpdateDirectionCmdPkg parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.chaoslabgames.packet.UpdateDirectionCmdPkg parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.chaoslabgames.packet.UpdateDirectionCmdPkg parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.chaoslabgames.packet.UpdateDirectionCmdPkg parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.chaoslabgames.packet.UpdateDirectionCmdPkg parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.chaoslabgames.packet.UpdateDirectionCmdPkg parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.chaoslabgames.packet.UpdateDirectionCmdPkg parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.chaoslabgames.packet.UpdateDirectionCmdPkg parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.chaoslabgames.packet.UpdateDirectionCmdPkg parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.chaoslabgames.packet.UpdateDirectionCmdPkg parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.chaoslabgames.packet.UpdateDirectionCmdPkg prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.chaoslabgames.packet.UpdateDirectionCmdPkg}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.chaoslabgames.packet.UpdateDirectionCmdPkg)
      com.chaoslabgames.packet.UpdateDirectionCmdPkgOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.chaoslabgames.packet.Packet.internal_static_com_chaoslabgames_packet_UpdateDirectionCmdPkg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.chaoslabgames.packet.Packet.internal_static_com_chaoslabgames_packet_UpdateDirectionCmdPkg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.chaoslabgames.packet.UpdateDirectionCmdPkg.class, com.chaoslabgames.packet.UpdateDirectionCmdPkg.Builder.class);
    }

    // Construct using com.chaoslabgames.packet.UpdateDirectionCmdPkg.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getDirectionFieldBuilder();
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      if (directionBuilder_ == null) {
        direction_ = com.chaoslabgames.packet.PointPkg.getDefaultInstance();
      } else {
        directionBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      tickId_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.chaoslabgames.packet.Packet.internal_static_com_chaoslabgames_packet_UpdateDirectionCmdPkg_descriptor;
    }

    public com.chaoslabgames.packet.UpdateDirectionCmdPkg getDefaultInstanceForType() {
      return com.chaoslabgames.packet.UpdateDirectionCmdPkg.getDefaultInstance();
    }

    public com.chaoslabgames.packet.UpdateDirectionCmdPkg build() {
      com.chaoslabgames.packet.UpdateDirectionCmdPkg result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.chaoslabgames.packet.UpdateDirectionCmdPkg buildPartial() {
      com.chaoslabgames.packet.UpdateDirectionCmdPkg result = new com.chaoslabgames.packet.UpdateDirectionCmdPkg(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      if (directionBuilder_ == null) {
        result.direction_ = direction_;
      } else {
        result.direction_ = directionBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.tickId_ = tickId_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.chaoslabgames.packet.UpdateDirectionCmdPkg) {
        return mergeFrom((com.chaoslabgames.packet.UpdateDirectionCmdPkg)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.chaoslabgames.packet.UpdateDirectionCmdPkg other) {
      if (other == com.chaoslabgames.packet.UpdateDirectionCmdPkg.getDefaultInstance()) return this;
      if (other.hasDirection()) {
        mergeDirection(other.getDirection());
      }
      if (other.hasTickId()) {
        setTickId(other.getTickId());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasDirection()) {
        
        return false;
      }
      if (!hasTickId()) {
        
        return false;
      }
      if (!getDirection().isInitialized()) {
        
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.chaoslabgames.packet.UpdateDirectionCmdPkg parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.chaoslabgames.packet.UpdateDirectionCmdPkg) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.chaoslabgames.packet.PointPkg direction_ = com.chaoslabgames.packet.PointPkg.getDefaultInstance();
    private com.google.protobuf.SingleFieldBuilder<
        com.chaoslabgames.packet.PointPkg, com.chaoslabgames.packet.PointPkg.Builder, com.chaoslabgames.packet.PointPkgOrBuilder> directionBuilder_;
    /**
     * <code>required .com.chaoslabgames.packet.PointPkg direction = 1;</code>
     */
    public boolean hasDirection() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.chaoslabgames.packet.PointPkg direction = 1;</code>
     */
    public com.chaoslabgames.packet.PointPkg getDirection() {
      if (directionBuilder_ == null) {
        return direction_;
      } else {
        return directionBuilder_.getMessage();
      }
    }
    /**
     * <code>required .com.chaoslabgames.packet.PointPkg direction = 1;</code>
     */
    public Builder setDirection(com.chaoslabgames.packet.PointPkg value) {
      if (directionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        direction_ = value;
        onChanged();
      } else {
        directionBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>required .com.chaoslabgames.packet.PointPkg direction = 1;</code>
     */
    public Builder setDirection(
        com.chaoslabgames.packet.PointPkg.Builder builderForValue) {
      if (directionBuilder_ == null) {
        direction_ = builderForValue.build();
        onChanged();
      } else {
        directionBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>required .com.chaoslabgames.packet.PointPkg direction = 1;</code>
     */
    public Builder mergeDirection(com.chaoslabgames.packet.PointPkg value) {
      if (directionBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001) &&
            direction_ != com.chaoslabgames.packet.PointPkg.getDefaultInstance()) {
          direction_ =
            com.chaoslabgames.packet.PointPkg.newBuilder(direction_).mergeFrom(value).buildPartial();
        } else {
          direction_ = value;
        }
        onChanged();
      } else {
        directionBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>required .com.chaoslabgames.packet.PointPkg direction = 1;</code>
     */
    public Builder clearDirection() {
      if (directionBuilder_ == null) {
        direction_ = com.chaoslabgames.packet.PointPkg.getDefaultInstance();
        onChanged();
      } else {
        directionBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }
    /**
     * <code>required .com.chaoslabgames.packet.PointPkg direction = 1;</code>
     */
    public com.chaoslabgames.packet.PointPkg.Builder getDirectionBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getDirectionFieldBuilder().getBuilder();
    }
    /**
     * <code>required .com.chaoslabgames.packet.PointPkg direction = 1;</code>
     */
    public com.chaoslabgames.packet.PointPkgOrBuilder getDirectionOrBuilder() {
      if (directionBuilder_ != null) {
        return directionBuilder_.getMessageOrBuilder();
      } else {
        return direction_;
      }
    }
    /**
     * <code>required .com.chaoslabgames.packet.PointPkg direction = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.chaoslabgames.packet.PointPkg, com.chaoslabgames.packet.PointPkg.Builder, com.chaoslabgames.packet.PointPkgOrBuilder> 
        getDirectionFieldBuilder() {
      if (directionBuilder_ == null) {
        directionBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.chaoslabgames.packet.PointPkg, com.chaoslabgames.packet.PointPkg.Builder, com.chaoslabgames.packet.PointPkgOrBuilder>(
                getDirection(),
                getParentForChildren(),
                isClean());
        direction_ = null;
      }
      return directionBuilder_;
    }

    private long tickId_ ;
    /**
     * <code>required int64 tickId = 2;</code>
     */
    public boolean hasTickId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 tickId = 2;</code>
     */
    public long getTickId() {
      return tickId_;
    }
    /**
     * <code>required int64 tickId = 2;</code>
     */
    public Builder setTickId(long value) {
      bitField0_ |= 0x00000002;
      tickId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int64 tickId = 2;</code>
     */
    public Builder clearTickId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      tickId_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.chaoslabgames.packet.UpdateDirectionCmdPkg)
  }

  static {
    defaultInstance = new UpdateDirectionCmdPkg(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:com.chaoslabgames.packet.UpdateDirectionCmdPkg)
}

