// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packages.proto

package com.chaoslabgames.packet;

public interface UpdateDirectionCmdPkgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.chaoslabgames.packet.UpdateDirectionCmdPkg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required .com.chaoslabgames.packet.PointPkg direction = 1;</code>
   */
  boolean hasDirection();
  /**
   * <code>required .com.chaoslabgames.packet.PointPkg direction = 1;</code>
   */
  com.chaoslabgames.packet.PointPkg getDirection();
  /**
   * <code>required .com.chaoslabgames.packet.PointPkg direction = 1;</code>
   */
  com.chaoslabgames.packet.PointPkgOrBuilder getDirectionOrBuilder();

  /**
   * <code>required int64 tickId = 2;</code>
   */
  boolean hasTickId();
  /**
   * <code>required int64 tickId = 2;</code>
   */
  long getTickId();
}
